[package]
name = "xxor"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "An enum for expressing two valid outcomes: XOR<This, That> means one or the other, never both."
readme = "readme.md"